name: build-env
channels:
  - conda-forge
dependencies:
  - jupytext
  - IPython
  - packaging
  - pip
  - jupyter_server
  - jupyterlite-core >=0.1.0,<0.2.0
  - pip:
    - jupyterlite-xeus-python >=0.8.1,<0.9.0
