name: build-env
channels:
  - conda-forge
dependencies:
  - scikit-learn >= 1.2.1
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - plotly >= 5.10
  - jupytext
  - beautifulsoup4
  - IPython
  - packaging
  - pip
