name: build-env
channels:
  - conda-forge
dependencies:
  - scikit-learn >= 1.2.1
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - plotly >= 5.10
  - jupytext
  - beautifulsoup4
  - IPython
  - packaging
  - pip
  - jupyter_server
  - jupyterlite-core >=0.1.0,<0.2.0
  - pip:
    - jupyterlite-xeus-python >=0.8.1,<0.9.0
