name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy >=1.21.6,<1.25.0
  - seaborn
  - plotly
  - beautifulsoup4
  - matplotlib
  - pandas
  - Pillow
  - scikit-learn >=1.0.0,<1.1.0

  
