name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - sklearn
  - pandas >=1
  - matplotlib-base
  - seaborn
  - plotly>=5.10
  - beautifulsoup4

  
