name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy >=1.17.2,<1.24.3
  - scikit-learn >=1.3.0
  - pandas >=1
  - matplotlib-base
  - seaborn
  - plotly>=5.10
  - beautifulsoup4

  
