name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - seaborn
  - plotly
  - beautifulsoup4
  - matplotlib
  - pandas
  - Pillow
  - joblib >=1.0.0
  - numpy >=1.20.3,<2.0
  - scipy
  - threadpoolctl >=2.0.0
  - scikit-learn

  
