name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy >=1.17.2,<1.24.3
  - scipy >= 0.19,!=1.0.0
  - scikit-learn >= 0.16
  - pandas >=1
  - matplotlib-base
  - seaborn
  - plotly>=5.10
  - beautifulsoup4

  
