name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - scikit-learn >= 1.2.1
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - plotly >= 5.10
  - IPython
  - packaging
