name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - seaborn
  - plotly
  - beautifulsoup4
  - matplotlib
  - pandas
  - Pillow
  - joblib >=1.0.0
  - libcblas >=3.9.0,<4.0
  - libgcc-ng >=12
  - libstdcxx-ng >=12
  - numpy >=1.20.3,<2.0
  - python >=3.9,<3.10.0a0
  - python >=3.9,<3.10.0a0 *_cpython
  - python_abi 3.9.* *_cp39
  - scipy
  - threadpoolctl >=2.0.0
  - scikit-learn

  
